### ISSUE TITLE
文章 No. 文章 ID

### ISSUE THREAD

**Issue by satopian** [satopian/poti-kaini-zh-TW#4]
![image](https://user-images.githubusercontent.com/44894014/116772439-0b7ecc00-aa8a-11eb-9d79-d7c6797905a0.png)
I changed it to "文章 No.". 
However, please let me know when the "文章 ID" is more appropriate.

**Comment by minchao** [comment]
That's my mistake.
Use "文章 No.", the text will be more consistent.

**Comment by satopian** [comment]
Thank you for teaching me.
