### ISSUE TITLE
替換舊圖片,發布新圖片

### ISSUE THREAD

**Issue by satopian** [satopian/poti-kaini-zh-TW#5]
```
<option value="rep">替換舊圖片</option>
<option value="new">發布新圖片</option>

```
When I first translated, the top and bottom of this part were swapped.
I'm not sure about the branch, so I'll attach a draft here.

```
<% def(newpost_nopassword) %>
<li>如如果是發布新圖片，則可以在沒有密碼的的情況下續繪。</li>
<% elsedef %>
<li>您必須輸入設定的續繪密碼才能繼續繪圖。</li>
<% /def %>

```
[pink_paint.html.zip](https://github.com/satopian/poti-kaini-zh-TW/files/6410791/pink_paint.html.zip)

**Comment by minchao** [comment]
@satopian Awesome, you really checked it very carefully. Will fix it in PR #3

**Comment by satopian** [comment]
```
<option value="rep">替換舊圖</option>  
<option value="new">新投稿</option>  
```
Thank you for the correction.  
Probably this is correct.  
However, i convert the Japanese "投稿" to Chinese, it becomes "帖子" and "發布".  
Google's translation may be wrong.  
Are the words used on the bulletin board the same for both Japanese "投稿" and Chinese "投稿"?  
Post→投稿(English→Japanese)  
投稿→投稿(日語→繁體中文)?

**Comment by minchao** [comment]
Sorry, I don't understand Japanese.
But, the "投稿" in Traditional Chinese means to submit piece of writing for publication, so "帖子" and "發布" are wrong.
I checked the below 和英辞典, their meaning should be the same. 😃 

https://ejje.weblio.jp/content/%E6%8A%95%E7%A8%BF

Yes, the term is also often used in Traditional Chinese BBS.

**Comment by satopian** [comment]
Thank you for explaining in detail.
