### ISSUE TITLE
palette.txt

### ISSUE THREAD

**Issue by satopian** [satopian/poti-kaini-zh-TW#6]
https://github.com/satopian/poti-kaini-zh-TW/blob/main/potiboard2/palette.txt

> hadairo,	膚色
> red,		紅色的
> yellow,		黃/橙
> green,		綠色的
> blue,		藍色的
> purple,		紫色的
> brown,		棕褐色
> character,	人,
> pastel,		柔和的
> sougen,		草地土地
> moe,		萌櫻花
> grayscale,	單色
> 
Please tell me a better translation.

**Comment by minchao** [comment]
@satopian I created a PR #7 for this.

**Comment by satopian** [comment]
Thank you very much.
Merged.

**Comment by satopian** [comment]
![image](https://user-images.githubusercontent.com/44894014/117331996-480b5700-aed2-11eb-8580-297e4c6268e5.png)
